### ISSUE TITLE
Failed to activate the package

### ISSUE THREAD

**Issue by Clyybber** [rm-code/love-atom#5]
Failed to activate the love-atom package
Cannot find module 'fuzzaldrin'
Traceback:
`Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Object.<anonymous> (/home/clyybber/.atom/packages/love-atom/lib/love-provider.coffee:3:11)
    at Object.<anonymous> (/home/clyybber/.atom/packages/love-atom/lib/love-provider.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/home/clyybber/.atom/packages/love-atom/lib/love-atom.coffee:2:16)
    at Object.<anonymous> (/home/clyybber/.atom/packages/love-atom/lib/love-atom.coffee:2:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Package.module.exports.Package.requireMainModule (/usr/lib/atom/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:173:16)
    at /usr/lib/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at /usr/lib/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
    at /usr/lib/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:489:46)
    at /usr/lib/atom/src/atom-environment.js:779:28
`

**Comment by rm-code** [comment]
Argh thanks for the report. Will look into it ASAP.

**Comment by rm-code** [comment]
@Clyybber Should be fixed with the latest version now. Could you please confirm?

**Comment by Clyybber** [comment]
Sry for my late answer, but yeah its fixed. Thank you.
